import { use } from 'react';
import type { DailyStory } from './dailyStories';
import { dailyStoryKeys } from './generated/dailyStoryKeys';

// Story bodies live in dailyStories.ts (single source of truth) but ship as one
// small chunk per story, generated by scripts/generate-daily-story-data.mjs.
// A story page downloads only the story it shows. Rendering is synchronous
// once a story is cached: the client preloads the current URL's story before
// the first render (main.tsx) and the prerender preloads all of them.
const bodies = import.meta.glob<DailyStory>('./generated/stories/*.json', { import: 'default' });
const loaded = new Map<string, DailyStory>();
const loading = new Map<string, Promise<DailyStory>>();

// A story is addressed by slug or by date (the date-alias URLs); slug wins.
export function findStoryDate(key: string | undefined): string | undefined {
  if (!key) return undefined;
  return (dailyStoryKeys.find(([, slug]) => slug === key) ?? dailyStoryKeys.find(([date]) => date === key))?.[0];
}

export function loadStory(key: string | undefined): Promise<DailyStory | undefined> {
  const date = findStoryDate(key);
  if (!date) return Promise.resolve(undefined);
  let pending = loading.get(date);
  if (!pending) {
    const load = bodies[`./generated/stories/${date}.json`];
    if (!load) return Promise.reject(new Error(`daily story data missing for ${date}; run npm run gen:daily-stories`));
    pending = load().then(
      (story) => {
        loaded.set(date, story);
        return story;
      },
      (error: unknown) => {
        loading.delete(date); // allow a retry after a network failure
        throw error;
      },
    );
    loading.set(date, pending);
  }
  return pending;
}

export function preloadAllStories(): Promise<unknown> {
  return Promise.all(dailyStoryKeys.map(([date]) => loadStory(date)));
}

// Suspends until the story is loaded. Never suspends when it is already cached.
export function useStory(key: string | undefined): DailyStory | undefined {
  const date = findStoryDate(key);
  if (!date) return undefined;
  return loaded.get(date) ?? use(loadStory(date) as Promise<DailyStory>);
}
